version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

    volumes:
      - ./data:/var/lib/postgresql/data

  phppgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pwd
    ports:
      - "8080:80"
    depends_on:
      - db


#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
#     networks:
#       - mon_reseau

# networks:
#   mon_reseau:
