version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  phppgadmin:
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpassfile:/pgpassfile
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pwd
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    image: webapp_code_barre
    ports:
      - "5000:5000"
    depends_on:
      - db
